---
- name: restart axon-dash
  service: name=axon-dash state=restarted
  when: docker is not defined

- name: reload nginx
  service:
    name: nginx
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes
