cassandra_cluster_name: default
cassandra_dc: default
cassandra_rack: rack1

cassandra_max_heap_size: 1G

cassandra_allocate_tokens_for_local_replication_factor: 3

# The user that will own the Cassandra binary files. Should normally be root.
cassandra_binary_owner: root
cassandra_binary_group: root

cassandra_version: 5.0.4
# valid options: tar
cassandra_install_format: tar
cassandra_install_root: /opt
cassandra_download_url: "https://downloads.apache.org/cassandra/{{ cassandra_version }}/apache-cassandra-{{ cassandra_version }}-bin.tar.gz"

cassandra_system_log_level: INFO

java_home: /usr/bin/java
cassandra_log_silence_status_logger: true
cassandra_dynamic_snitch_enabled: true

cassandra_gc_log_dir: /var/log/cassandra
cassandra_log_dir: /var/log/cassandra
cassandra_saved_caches_directory: /var/lib/cassandra/saved_caches
cassandra_data_directory: /var/lib/cassandra
cassandra_hints_directory: /var/lib/cassandra/hints
cassandra_start_on_boot: true
cassandra_auto_bootstrap: true
cassandra_symlink_homedir: true
cassandra_jmx_port: 7199
cassandra_jna_tmp_dir: /tmp
cassandra_java_tmp_dir: /tmp

cassandra_log_outbound_tcp_connection: disabled
cassandra_log_debug_repairs: disabled

# Anything additional to add to the end of cassandra-env.sh, one line per array entry
cassandra_env_extra: []

# cassandra_transparent_data_encryption_options:
#   enabled: false
#   chunk_length_kb: 64
#   cipher: AES/CBC/PKCS5Padding
#   key_alias: testing:1
#   # CBC IV length for AES needs to be 16 bytes (which is also the default size)
#   # iv_length: 16
#   key_provider:
#     - class_name: org.apache.cassandra.security.JKSKeyProvider
#       parameters:
#         - keystore: /opt/ssl-certs/keystore.jks
#           keystore_password: cassandra
#           store_type: JCEKS
#           key_password: cassandra
