cassandra_cluster_name: default
cassandra_dc: default
cassandra_rack: rack1

cassandra_max_heap_size: 1G

cassandra_allocate_tokens_for_local_replication_factor: 3

# The user that will own the Cassandra binary files. Should normally be root.
cassandra_binary_owner: root
cassandra_binary_group: root

cassandra_version: 5.0.4

cassandra_cqlsh_binary_version: 0.1.3
cassandra_cqlsh_binary: "{{ _cassandra_cqlsh_binary }}"

# It is recommended to leave this as false
cassandra_start_on_boot: false

# valid options: tar or pkg
cassandra_install_format: pkg
cassandra_install_root: /opt
cassandra_download_url: "https://downloads.apache.org/cassandra/{{ cassandra_version }}/apache-cassandra-{{ cassandra_version }}-bin.tar.gz"

cassandra_system_log_level: INFO

java_home: /usr/bin/java
cassandra_log_silence_status_logger: true
cassandra_dynamic_snitch_enabled: true

cassandra_gc_log_dir: /var/log/cassandra
cassandra_log_dir: /var/log/cassandra
cassandra_saved_caches_directory: /var/lib/cassandra/saved_caches
cassandra_data_directory: /var/lib/cassandra
cassandra_hints_directory: /var/lib/cassandra/hints
cassandra_commitlog_directory: "/var/lib/cassandra/commitlog"
cassandra_auto_bootstrap: true
cassandra_symlink_homedir: true
cassandra_jmx_port: 7199
cassandra_jna_tmp_dir: /tmp
cassandra_java_tmp_dir: /tmp

cassandra_log_outbound_tcp_connection: disabled
cassandra_log_debug_repairs: disabled

# Anything additional to add to the end of cassandra-env.sh, one line per array entry
cassandra_env_extra: []

# cassandra_transparent_data_encryption_options:
#   enabled: false
#   chunk_length_kb: 64
#   cipher: AES/CBC/PKCS5Padding
#   key_alias: testing:1
#   # CBC IV length for AES needs to be 16 bytes (which is also the default size)
#   # iv_length: 16
#   key_provider:
#     - class_name: org.apache.cassandra.security.JKSKeyProvider
#       parameters:
#         - keystore: /opt/ssl-certs/keystore.jks
#           keystore_password: cassandra
#           store_type: JCEKS
#           key_password: cassandra

# Cluster Configuration
cassandra_num_tokens: 32

# Hints Configuration
cassandra_hinted_handoff_enabled: true
# cassandra_max_hint_window: "3h"
# cassandra_hinted_handoff_throttle: "1024KiB"
cassandra_max_hints_delivery_threads: 2
# cassandra_hints_flush_period: "10s"
# cassandra_max_hints_file_size: "128MiB"
cassandra_auto_hints_cleanup_enabled: true
cassandra_transfer_hints_on_decommission: true

# Batch Log Configuration
cassandra_batchlog_replay_throttle: "1024KiB"

# Authentication and Authorization
cassandra_authenticator_class_name: "PasswordAuthenticator"
cassandra_authorizer: "CassandraAuthorizer"
cassandra_role_manager: "CassandraRoleManager"
cassandra_network_authorizer: "AllowAllNetworkAuthorizer"
cassandra_cidr_authorizer_class_name: "AllowAllCIDRAuthorizer"
cassandra_authenticator: PasswordAuthenticator
cassandra_internode_authenticator: org.apache.cassandra.auth.AllowAllInternodeAuthenticator
cassandra_cidr_checks_for_superusers: false
cassandra_cidr_authorizer_mode: "MONITOR"
cassandra_cidr_groups_cache_refresh_interval: 5
cassandra_ip_cache_max_size: 100

# # Cache Configuration
# # cassandra_roles_validity: "120s"
# # cassandra_roles_update_interval: "10s"
# # cassandra_permissions_validity: "60s"
# # cassandra_permissions_update_interval: "10s"
# # cassandra_credentials_validity: "120s"
# # cassandra_credentials_update_interval: "10s"

# Partitioner
cassandra_partitioner: "org.apache.cassandra.dht.Murmur3Partitioner"

# CDC Configuration
cassandra_cdc_enabled: false
cassandra_cdc_block_writes: true
cassandra_cdc_on_repair_enabled: true
cassandra_cdc_raw_directory: "/var/lib/cassandra/cdc_raw"

# Failure Policies
cassandra_disk_failure_policy: "die"
cassandra_commit_failure_policy: "die"

# Cache Settings
cassandra_prepared_statements_cache_size: "24MiB"
cassandra_key_cache_size: "512MiB"
cassandra_key_cache_save_period: "4h"
cassandra_row_cache_class_name: "org.apache.cassandra.cache.OHCProvider"
cassandra_row_cache_size: "0MiB"
cassandra_row_cache_save_period: "0s"
cassandra_counter_cache_size: ""
cassandra_counter_cache_save_period: "2h"
cassandra_cache_load_timeout: "2m"

# Commit Log Configuration
cassandra_commitlog_sync: "periodic"
cassandr_commitlog_sync_period: "10s"
cassandra_commitlog_segment_size: "32MiB"

# Seed Configuration
cassandra_seeds: "127.0.0.1"

# Concurrency Settings
cassandra_concurrent_reads: 32
cassandra_concurrent_writes: 32
cassandra_concurrent_counter_writes: 32
cassandra_concurrent_materialized_view_writes: 32

# Disk Optimization
cassandra_disk_optimization_strategy: "ssd"

# Memtable Configuration
cassandra_memtable_allocation_type: "offheap_objects"

# Compaction Settings
cassandra_concurrent_compactors: 1
cassandra_concurrent_materialized_view_builders: 1
cassandra_uuid_sstable_identifiers_enabled: false
cassandra_compaction_throughput: "64MiB/s"
cassandra_sstable_preemptive_open_interval: "64MiB"

# Streaming Configuration
cassandra_entire_sstable_stream_throughput_outbound: "24MiB/s"
cassandra_entire_sstable_inter_dc_stream_throughput_outbound: "24MiB/s"
cassandra_stream_throughput_outbound: "24MiB/s"
cassandra_inter_dc_stream_throughput_outbound: "24MiB/s"

# Request Timeouts
cassandra_read_request_timeout: "5s"
cassandra_range_request_timeout: "10s"
cassandra_write_request_timeout: "2s"
cassandra_counter_write_request_timeout: "5s"
cassandra_cas_contention_timeout: "1s"
cassandra_truncate_request_timeout: "60s"
cassandra_request_timeout: "10s"

# Network Configuration
cassandra_storage_port: 7000
cassandra_ssl_storage_port: 7001
cassandra_listen_address: "{{ ansible_default_ipv4.address | default('localhost') }}"
cassandra_internode_authenticator_class_name: "org.apache.cassandra.auth.AllowAllInternodeAuthenticator"
cassandra_start_native_transport: true
cassandra_native_transport_port: 9042
cassandra_native_transport_allow_older_protocols: true
cassandra_rpc_address: "{{ ansible_default_ipv4.address | default('localhost') }}"
cassandra_rpc_keepalive: true

# Internode TCP Configuration
cassandra_internode_tcp_connect_timeout: "2000ms"
cassandra_internode_tcp_user_timeout: "30s"
cassandra_internode_streaming_tcp_user_timeout: "5m"
cassandra_internode_timeout: true

# Slow Query Configuration
cassandra_slow_query_log_timeout: "500ms"

# Phi Convict Threshold
cassandra_phi_convict_threshold: 12

# Endpoint Snitch
cassandra_endpoint_snitch: "GossipingPropertyFileSnitch"

# Dynamic Snitch Configuration
cassandra_dynamic_snitch_update_interval: "100ms"
cassandra_dynamic_snitch_reset_interval: "10m"
cassandra_dynamic_snitch_badness_threshold: "0.1"

# Crypto Provider
crypto_provider_class_name: "org.apache.cassandra.security.DefaultCryptoProvider"
crypto_provider_parameters_fail_on_missing_provider: false

# SSL Configuration
cassandra_ssl_internode_encryption: "none"
cassandra_ssl_internode_require_client_auth: false
cassandra_require_endpoint_verification: false
cassandra_legacy_ssl_storage_port_enabled: false
cassandra_ssl_internode_keystore_file: "conf/.keystore"
cassandra_ssl_internode_keystore_pass: "cassandra"
cassandra_ssl_truststore_file: "conf/.truststore"
cassandra_ssl_truststore_pass: "cassandra"
cassandra_server_encryption_options_require_client_auth: false
cassandra_server_encryption_options_require_endpoint_verification: false
cassandra_ssl_internode_protocol: "TLS"

# Client SSL Configuration
cassandra_ssl_client_encryption_enabled: false
cassandra_ssl_client_encryption_optional: true
cassandra_ssl_client_keystore_file: "conf/.keystore"
cassandra_ssl_client_keystore_pass: "cassandra"
cassandra_ssl_client_require_client_auth: false
cassandra_ssl_client_require_endpoint_verification: false
cassandra_ssl_client_encryption_protocol: "TLS"

# Internode Compression
cassandra_internode_compression: "dc"
cassandra_inter_dc_tcp_nodelay: false

# Backup Configuration
cassandra_incremental_backups: false
cassandra_snapshot_before_compaction: false
cassandra_auto_snapshot: true
cassandra_snapshot_links_per_second: 16384

# SSTable Configuration
cassandra_sstable_selected_format: "bti"
cassandra_column_index_cache_size: "2KiB"

# Default Compaction Strategy
default_compaction:
  class_name: "UnifiedCompactionStrategy"
  parameters:
    scaling_parameters: "T4"
    target_sstable_size: "1GiB"

# Trickle Fsync
cassandra_trickle_fsync: true
cassandra_trickle_fsync_interval: "10MiB"

# Index Summary
cassandra_index_summary_capacity: ""
cassadra_index_summary_resize_interval: "60m"

# Safety Thresholds
cassandra_tombstone_warn_threshold: 1000
cassandra_tombstone_failure_threshold: 100000
cassandra_replica_filtering_protection_cached_rows_warn_threshold: 2000
replica_filtering_protection_cached_rows_fail_threshold: 32000
cassandra_batch_size_warn_threshold: "64KiB"
cassandra_batch_size_fail_threshold: "640KiB"
cassandra_unlogged_batch_across_partitions_warn_threshold: 10

# GC Configuration
cassandra_gc_log_threshold: "200ms"
cassandra_gc_warn_threshold: "1000ms"

# Experimental Features
cassandra_materialized_views_enabled: false
cassandra_sasi_indexes_enabled: false
cassandra_transient_replication_enabled: false
cassandra_drop_compact_storage_enabled: false

# Diagnostic Events
cassandra_diagnostic_events_enabled: false

# Repaired Data Tracking
cassandra_repaired_data_tracking_for_range_reads_enabled: false
cassandra_repaired_data_tracking_for_partition_reads_enabled: false
cassandra_report_unconfirmed_repaired_data_mismatches: false

cassandra_column_index_size: 64KiB

# Transparent Data Encryption (disabled by default)
cassandra_transparent_data_encryption_options:
  enabled: false
  chunk_length_kb: 64
  cipher: "AES/CBC/PKCS5Padding"
  key_alias: "testing:1"
  key_provider:
    - class_name: "org.apache.cassandra.security.JKSKeyProvider"
      parameters:
        - keystore: "conf/.keystore"
          keystore_password: "cassandra"
          store_type: "JCEKS"
          key_password: "cassandra"

# JVM
cassandra_jvm_use_shenandoah: false
cassandra_max_queued_native_transport_requests: 1024
cassandra_jvm_g1_rset_updating_pause_time_percent: 5
cassandra_jvm_max_gc_pause_ms: 500
cassandra_jvm_initiating_heap_occupancy_percentage: 40
cassandra_jvm_gc_log_file_number: 10
cassandra_jvm_gc_log_file_max_size_mb: 10
cassandra_jvm_parallel_gc_threads: 4
cassandra_jvm_conc_gc_threads: 4
