- name: Deploy AxonOps Agent
  hosts: cassandra
  become: true
  vars:
    axon_java_agent: "axon-cassandra4.1-agent"
    axon_agent_version: "1.0.131"
    axon_java_agent_version: "1.0.14"
    customer_name: example
    java_pkg: java-11-openjdk-headless
    # Set to false if you already have Apache Cassandra running
    install_cassandra: true

  roles:
    - role: agent
      tags: agent, axonops-agent
      vars:
        axon_agent_server_host: "{{ groups['axon-server'] | first }}"
        cassandra_dc: "DC1"
        cassandra_seeds: "{{ groups['cassandra'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list | first }}"
    - role: cassandra
      tags: cassandra
      when: install_cassandra
      vars:
        cassandra_dc: "example"

  post_tasks:
    - name: Add axonops to the cassandra group
      tags: user
      ansible.builtin.user:
        name: cassandra
        groups: cassandra,axonops
        append: true
      notify:
        - restart axon-agent
        - Restart Cassandra

# code: language=ansible
