- name: Deploy AxonOps Server
  hosts: axon-server
  become: true
  vars:
    install_cassandra: true
    install_elastic: true
    axon_server_cql_hosts:
      - localhost:9042
    axon_dash_listen_address: 0.0.0.0
    axon_agent_redhat_repository: "https://packages.axonops.com/yum"
    es_redhat_repository_url: https://artifacts.elastic.co/packages/7.x/yum
    cassandra_cluster_name: axonops
    cassandra_dc: default
    cassandra_rack: rack1
    axon_java_agent: "axon-cassandra5.0-agent-jdk17"
    axon_agent_server_host: localhost
    axon_agent_tls_mode: "disabled"
    axon_agent_customer_name: "mycompany"
    cassandra_start_on_boot: true
    cassandra_listen_address: "localhost"
    cassandra_rpc_address: "localhost"


  pre_tasks:
    # This is only for this example to work, please review your firewall settings and requirements
    - name: "Stop firewalld"
      ansible.builtin.systemd:
        name: firewalld
        enabled: false
        state: stopped
      when: ansible_os_family == 'RedHat'
      failed_when: false

  roles:
    - name: java
      role: java
      tags: java
    - role: agent
      tags: agent, axonops-agent
    - role: cassandra
      tags: cassandra
      when: install_cassandra is defined and install_cassandra
    - role: elastic
      tags: elastic
      when: install_elastic is defined and install_elastic
    - role: server
      tags: server, axonops-server
    - role: dash
      tags: dash, axonops-dashboard

# code: language=ansible
