roles: []
collections:
  - name: community.general
    source: https://galaxy.ansible.com
  - name: ansible.posix
    source: https://galaxy.ansible.com
  - name: community.crypto
    source: https://galaxy.ansible.com
  - name: axonops.axonops
    source: https://github.com/axonops/axonops-ansible-collection
    version: main
    type: git
  - name: devsec.hardening
    source: https://galaxy.ansible.com
    version: 10.3.0
