- name: Start or restart Cassandra and AxonOps Agent (SEEDS Only)
  hosts: "cassandra"
  become: true
  serial: 1
  vars:
    state: started
  tasks:
    - name: Exist if not a seed node
      meta: end_play
      when: not inventory_hostname in cassandra_seeds

    - name: Start Cassandra service
      ansible.builtin.service:
        name: cassandra
        state: "{{ state }}"

    - name: Start AxonOps Agent
      ansible.builtin.service:
        name: axon-agent
        state: "{{ state }}"

    - name: Wait for Cassandra to be up and running
      ansible.builtin.wait_for:
        port: 9042
        host: "{{ cassandra_rpc_address | default(ansible_default_ipv4.address) | default('localhost') }}"
        timeout: 300
        state: started

- name: Start or restart Cassandra and AxonOps Agent (Non Seeds)
  hosts: "cassandra"
  become: true
  serial: 1
  vars:
    state: started
  tasks:
    - name: Exist if a seed node
    - meta: end_play
      when: inventory_hostname in cassandra_seeds

    - name: Start Cassandra service
      ansible.builtin.service:
        name: cassandra
        state: "{{ state }}"

    - name: Start AxonOps Agent
      ansible.builtin.service:
        name: axon-agent
        state: "{{ state }}"

    - name: Wait for Cassandra to be up and running
      ansible.builtin.wait_for:
        port: 9042
        host: "{{ cassandra_rpc_address | default(ansible_default_ipv4.address) | default('localhost') }}"
        timeout: 300
        state: started

# code: language=ansible
