galaxy_info:
  author: AxonOps Limited
  description: This role installs and configures the AxonOps dashboard
  company: AxonOps Limited
  license: Apache 2.0
  min_ansible_version: "2.10"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - "20.04"
        - "22.04"

  galaxy_tags:
  - axonops
  - agent
  - dashboard

  dependencies: []
  documentation: https://github.com/axonops/axonops-ansible-collection
  issues: https://github.com/axonops/axonops-ansible-collection/issues
