---
- name: Set config directory if not set
  tags: always
  ansible.builtin.set_fact:
    cassandra_conf_dir: "{{ cassandra_install_root }}/apache-cassandra-{{ cassandra_version }}/conf"
    cassandra_install_dir: "{{ cassandra_install_root }}/apache-cassandra-{{ cassandra_version }}"
    cassandra_home_dir: "{{ cassandra_install_root }}/cassandra"

- name: Create the Cassandra user
  ansible.builtin.user:
    name: cassandra
    home: "{{ cassandra_log_dir }}"
    shell: /bin/bash
    comment: "Created by Ansible"

- name: Cassandra binaries
  ansible.builtin.unarchive:
    src: "{{ cassandra_download_url }}"
    dest: "{{ cassandra_install_root }}"
    remote_src: true
    owner: "{{ cassandra_binary_owner | default('cassandra') }}"
    group: "{{ cassandra_binary_group | default('cassandra') }}"
    creates: "{{ cassandra_conf_dir }}"

- name: "Ensure Cassandra install directory has the correct owner"
  ansible.builtin.file:
    path: "{{ cassandra_install_dir }}"
    state: directory
    owner: "{{ cassandra_binary_owner | default('cassandra') }}"
    group: "{{ cassandra_binary_group | default('cassandra') }}"
    mode: 0755

- name: Symlink to the apache-cassandra folder
  ansible.builtin.file:
    state: link
    src: "{{ cassandra_install_dir }}"
    dest: "{{ cassandra_home_dir }}"
    force: true

- name: Add Cassandra to the profile path
  tags: profile,cassandra,cassandra_profile
  when: cassandra_bash_profile
  ansible.builtin.copy:
    dest: /etc/profile.d/cassandra.sh
    content: |
      export CASSANDRA_HOME={{ cassandra_home_dir }}
      export PATH=$PATH:$CASSANDRA_HOME/bin
      {% if cassandra_jmx_password is defined and cassandra_jmx_password != "" %}
      alias nodetool='nodetool -u {{ cassandra_jmx_user | default("cassandra") }} -pwf {{ cassandra_jmx_password_file }}'
      {% else %}
      {% endif %}
    mode: '0644'

# code: language=ansible
