- name: Install from pkg
  when: cassandra_install_format == "pkg"
  ansible.builtin.import_tasks: install-pkg.yml

- name: Install from tar
  when: cassandra_install_format == "tar"
  ansible.builtin.import_tasks: install-tar.yml

- name: Create main directories
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0750"
    owner: "cassandra"
    group: "cassandra"
    state: directory
  with_items:
    - "{{ cassandra_log_dir }}"
    - "{{ cassandra_hints_directory }}"
    - "{{ cassandra_gc_log_dir }}"
    - "{{ cassandra_saved_caches_directory }}"
    - "{{ cassandra_data_directory }}"

- name: Deploy configuration
  tags: config
  block:
    - name: Template directory
      ansible.builtin.set_fact:
        tmpl_dir: 5.0.x
      when: cassandra_version.startswith('5.')

    - name: Template directory
      ansible.builtin.set_fact:
        tmpl_dir: 4.1.x
      when: cassandra_version.startswith('4.1')

    - name: Ensure Cassandra node configured
      #notify: Restart Cassandra
      ansible.builtin.template:
        src: "{{ tmpl_dir }}/{{ item }}.j2"
        dest: "{{ cassandra_conf_dir | default('/etc/cassandra') }}/{{ item }}"
        mode: "0644"
      with_items:
        - cassandra-env.sh
        - cassandra-rackdc.properties
        - cassandra.yaml
        - logback.xml
        - jvm-server.options
        - jvm11-server.options
        - jvm-clients.options
        - jvm11-clients.options

- name: Systemd service for cassandra
  ansible.builtin.template:
    dest: /etc/systemd/system/cassandra.service
    src: templates/cassandra.service.j2
    mode: "0644"
    owner: root
    group: root
  notify: Reload systemd

- name: Start cassandra
  tags: service
  ansible.builtin.systemd:
    name: cassandra
    enabled: true
    state: started
  when: cassandra_start_on_boot is defined and cassandra_start_on_boot

# code: language=ansible
