---
# https://github.com/apache/cassandra/blob/18bcda2d4c2eba7370a0b21f33eed37cb730bbb3/bin/cassandra#L90-L100
- name: Install numactl
  ansible.builtin.package:
    name: numactl
    state: latest

- name: Minimal VM swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "1"

- name: Configure sysctl settings for Cassandra
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/99-cassandra.conf
  loop:
    - { name: "vm.overcommit_memory", value: "1" }
    - { name: "vm.max_map_count", value: "1048575" }
    - { name: "net.ipv4.tcp_keepalive_time", value: "300" }
    - { name: "net.core.rmem_max", value: "16777216" }
    - { name: "net.core.wmem_max", value: "16777216" }
    - { name: "net.core.rmem_default", value: "16777216" }
    - { name: "net.core.wmem_default", value: "16777216" }
    - { name: "net.core.optmem_max", value: "40960" }
    - { name: "net.ipv4.tcp_rmem", value: "4096 87380 16777216" }
    - { name: "net.ipv4.tcp_wmem", value: "4096 65536 16777216" }
  tags:
    - cassandra
    - sysctl
    - performance

- name: Setup irqbalance
  ansible.builtin.copy:
    mode: "0644"
    owner: root
    dest: /etc/default/irqbalance
    content: |
      # Managed by Ansible
      #Configuration for the irqbalance daemon

      #Should irqbalance be enabled?
      ENABLED="0"
      #Balance the IRQs only once?
      ONESHOT="0"

- name: Cassandra User Limits
  ansible.builtin.copy:
    dest: /etc/security/limits.d/cassandra.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      # Managed by Ansible

      cassandra  -  memlock  unlimited
      cassandra  -  nofile   1000000
      cassandra  -  as       unlimited
      cassandra  -  nproc    32768

# code: language=ansible
