---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart pki-agent
  ansible.builtin.systemd:
    name: openbao-agent
    state: restarted
    daemon_reload: true

# code: language=ansible
