---
- name: Add AxonOps yum repository
  yum_repository:
    name: axonops-yum
    description: "AxonOps Repository"
    baseurl: "{{ axon_agent_redhat_repository | default('https://packages.axonops.com/yum') }}"
    repo_gpgcheck: false
    gpgcheck: false

# code: language=ansible
