---
- name: "Retrieve AxonOps cluster health info for {{ org ~ '/' ~ cluster }}"
  axonops.axonops.info:
    org: "{{ org }}"
    cluster: "{{ cluster }}"
    cluster_type: "{{ cluster_type | default(omit) }}"
    base_url: "{{ base_url | default(omit) }}"
    username: "{{ username | default(omit) }}"
    password: "{{ password | default(omit) }}"
    auth_token: "{{ auth_token | default(omit) }}"
    api_token: "{{ api_token | default(omit) }}"
    override_saas: "{{ override_saas | default(omit) }}"
    use_saml: "{{ use_saml | default(omit) }}"
    validate_certs: "{{ validate_certs | default(omit) }}"
  tags:
  - info
  - never

# code: language=ansible
