---
- name: Initialize axonops_pagerduty_integrations
  tags: always
  ansible.builtin.set_fact:
    axonops_pagerduty_integrations: []
  when: axonops_pagerduty_integrations is not defined

- name: Load organization-wide PagerDuty integration rules
  tags: always
  ansible.builtin.set_fact:
    axonops_pagerduty_integrations: "{{ axonops_pagerduty_integrations + (lookup('file', item) | from_yaml).axonops_pagerduty_integrations }}"
  with_fileglob:
    - "config/{{ org }}/pagerduty_integrations.yml"

- name: Load cluster-specific PagerDuty integration rules
  tags: always
  ansible.builtin.set_fact:
    axonops_pagerduty_integrations: "{{ axonops_pagerduty_integrations + (lookup('file', item) | from_yaml).axonops_pagerduty_integrations }}"
  with_fileglob:
    - "config/{{ org }}/{{ cluster }}/pagerduty_integrations.yml"

- name: "Install PagerDuty integrations on {{ org }}/{{ cluster }}"
  axonops.axonops.pagerduty_integration:
    org: "{{ org }}"
    cluster: "{{ cluster }}"
    cluster_type: "{{ pagerduty_item.cluster_type | default(cluster_type | default(omit)) }}"
    name: "{{ pagerduty_item.name }}"
    integration_key: "{{ pagerduty_item.integration_key }}"
    present: "{{ pagerduty_item.present | default(true) }}"
    base_url: "{{ base_url | default(omit) }}"
    auth_token: "{{ pagerduty_item.auth_token | default(auth_token | default(omit)) }}"
    api_token: "{{ pagerduty_item.api_token | default(api_token | default(omit)) }}"
    username: "{{ pagerduty_item.username | default(username | default(omit)) }}"
    password: "{{ pagerduty_item.password | default(password | default(omit)) }}"
    override_saas: "{{ override_saas | default(omit) }}"
    use_saml: "{{ use_saml | default(omit) }}"
    validate_certs: "{{ validate_certs | default(omit) }}"
  loop: "{{ axonops_pagerduty_integrations }}"
  no_log: "{{ false if enable_logging is defined and enable_logging else true }}"
  loop_control:
    loop_var: pagerduty_item
  tags:
    - axonops_pagerduty_integrations
    - pagerduty_integrations
    - pagerduty_integration
    - integration
    - pagerduty

# code: language=ansible
