---
- name: Initialize axonops_teams_integrations
  tags: always
  ansible.builtin.set_fact:
    axonops_teams_integrations: []
  when: axonops_teams_integrations is not defined

- name: Load organization-wide Teams integration rules
  tags: always
  ansible.builtin.set_fact:
    axonops_teams_integrations: "{{ axonops_teams_integrations + (lookup('file', item) | from_yaml).axonops_teams_integrations }}"
  with_fileglob:
    - "config/{{ org }}/teams_integrations.yml"

- name: Load cluster-specific Teams integration rules
  tags: always
  ansible.builtin.set_fact:
    axonops_teams_integrations: "{{ axonops_teams_integrations + (lookup('file', item) | from_yaml).axonops_teams_integrations }}"
  with_fileglob:
    - "config/{{ org }}/{{ cluster }}/teams_integrations.yml"

- name: "Install Teams integrations {{ org }}/{{ cluster }}"
  axonops.axonops.teams_integration:
    org: "{{ org }}"
    cluster: "{{ cluster }}"
    cluster_type: "{{ teams_item.cluster_type | default(cluster_type | default(omit)) }}"
    present: "{{ teams_item.present | default(true) }}"
    name: "{{ teams_item.name }}"
    webhook_url: "{{ teams_item.webhook_url }}"
    base_url: "{{ base_url | default(omit) }}"
    auth_token: "{{ teams_item.auth_token | default(auth_token | default(omit)) }}"
    api_token: "{{ teams_item.api_token | default(api_token | default(omit)) }}"
    username: "{{ teams_item.username | default(username | default(omit)) }}"
    password: "{{ teams_item.password | default(password | default(omit)) }}"
    override_saas: "{{ override_saas | default(omit) }}"
    use_saml: "{{ use_saml | default(omit) }}"
    validate_certs: "{{ validate_certs | default(omit) }}"
  loop: "{{ axonops_teams_integrations }}"
  no_log: "{{ false if enable_logging is defined and enable_logging else true }}"
  loop_control:
    loop_var: teams_item
  tags:
    - axonops_teams_integrations
    - teams_integrations
    - teams_integration
    - integration
    - teams

# code: language=ansible
