# This file contains sensitive information and should be protected.
# Use Ansible Vault to encrypt this file.

# vault_ssl_key: |
#   Bag Attributes
#       friendlyName: cassandra.example.com
#       localKeyID: 54 69 6D 65 20 31 37 34 39 38 32 37 31 34 32 34 39 37
#   Key Attributes: <No Attributes>
#   -----BEGIN PRIVATE KEY-----
#   MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCS+ON15uGOPu1W
#   +nBYA7FMCJotWNhFNbZL7f0u8p1g5SUrFjJD24nr/bLrhRoVuhLw4kiqXo0sPtIt
#   bjk51MO8yqHe8ePm/sgYaVElWcwSGUfXrZFWkmTF6ULZz5yiqFHeRvtVpc1sfE8n
#   uLyBuaP7llzLvvowoFkpXfNFh3WNdFu78ZSjoEf8UD77cw1RmYxdMRobN2YIHB6G
#   qaT6IL5zyEDcFuDpracBCfNvkNmL8JAqnmjmsrZWHTOp5oOzCols4I443LjiVtaC
#   D2VpPb3J+ROxp+VNmMHld4envqatv4uA1kwwbADxeCxRoVV7mFpo/tRXew7IIHob
#   m0sJEtM5AgMBAAECggEAEQti8q6P0DOxSe3hlz13Y2xYeAOWkkEyRuA+5WHO2Vi9
#   vJ9WfTrhxf/uLuTo42Xo0i2F9JciS2QuMwVWRuQLPrLnvp+iGO0JhtY46kpdkahD
#   pgo7oZT48aBVh8XNYio/01W7SmGf/xG0CtTgbLF7KF9V2+2mHXtNF9Bs2O6GlhzA
#   SEIK/03SbmzQZ3nwaJgUGaV2dRzix88cnjY94aTk3UsANSenQ9KEcyW78B0q5PAv
#   mJT52Y3Ucjm6e7mnchPe7tesrs/nFzzQyO94OgaIjhuDtOHIHyzs460zM6tKulFJ
#   0/P42X6fCzFT+Vp40pBZRsCgQa3U1Tfq6vkemKshoQKBgQC5MGIlbhyTJFfHkWhU
#   pBzWizSSWTgnZk0tppXVA0CcAxtunv6zc55c6Xv3YV2VWmhJJ0rKmGVnL2L824c/
#   KTLPtY6TNLR74CVdFqxidQq9NmzMh9InxWnMw7LG7eCKYjVV6zGvoErdVvhtceqx
#   U/wHdP0e1rde1oEwxhC8qBvhmQKBgQDLK5M7YHLv7Vi1HGI1D9/SsPZ6AR1wwOjO
#   r15lH3mKmfDUm6eKqEq9BiFePbKQqXTTFvYM8ZBMr7ZwVmYQ237PxEr2CS+FbxeT
#   bCCsKZ19ukBGfkX0IgBqHLemdC/jBcuf1Qx5YfkDcWTOe90EPc06Ye3CnLBAhkWO
#   Rw+JZ7TCoQKBgEDHkP2A6BP8mYwg7Dr3cXMHHOu4s/DsU0ENzcnGqnooiBcJHRWO
#   8y2TKx8c+wx8pJA6Y2o9JvOSWvESpdvNQI3x9568yAmxHcDTZpfGU2xetm5RcI0i
#   /GB5cHcvzOT7d6bHcAj8bFPC0YIPYEaJl1bQcJ6yA1D0fhqenkowEBi5AoGADfpw
#   hcxL/B/rU4Khax8tehR80MYU3XYYTmgYaYKx3QxcWnRfIZYUlk6+qvo5t+RAymkx
#   ApD4KZ6JQc9f9Fb1sZvCwIy/PUH4cEcnNFEkqcrPs0nqzDIurx5MsGIcDVWPve5t
#   jkhkVo1NrzssaKdL4HFuZ05afgX+8RwIgJ6m/CECgYBeu8xcb/K+zmMHRM99Cl+g
#   ak4WU0chT3g0YNQefPDJaU/i7asKVnIABPzqYVSZbb3n0FDtDnzFQWORca5Jk51u
#   bdURv3sEyPahc4f2tfTamNz1SXtBv8Ycq50k2Stb2Xkbgw0vOnmmdy2r/94JY0mC
#   DOeN4cs09iCjaGvqz3D9JQ==
#   -----END PRIVATE KEY-----

# vault_ssl_crt: |
#   -----BEGIN CERTIFICATE-----
#   MIIDXzCCAkcCFBEPu+zMKZaqTewnocE00x/dRhNpMA0GCSqGSIb3DQEBCwUAMFMx
#   CzAJBgNVBAYTAkdCMR0wGwYDVQQKDBRkaWdpdGFsaXMuaW8gTGltaXRlZDEUMBIG
#   A1UECwwLVGVzdENsdXN0ZXIxDzANBgNVBAMMBnJvb3RDYTAeFw0yNTA2MTMxNTA1
#   NDBaFw0zNTA2MTExNTA1NDBaMIGEMQswCQYDVQQGEwJHQjEPMA0GA1UECBMGTG9u
#   ZG9uMQ8wDQYDVQQHEwZMb25kb24xHTAbBgNVBAoTFGRpZ2l0YWxpcy5pbyBMaW1p
#   dGVkMRQwEgYDVQQLEwtUZXN0Q2x1c3RlcjEeMBwGA1UEAxMVY2Fzc2FuZHJhLnJv
#   b3RhcHAuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkvjjdebh
#   jj7tVvpwWAOxTAiaLVjYRTW2S+39LvKdYOUlKxYyQ9uJ6/2y64UaFboS8OJIql6N
#   LD7SLW45OdTDvMqh3vHj5v7IGGlRJVnMEhlH162RVpJkxelC2c+coqhR3kb7VaXN
#   bHxPJ7i8gbmj+5Zcy776MKBZKV3zRYd1jXRbu/GUo6BH/FA++3MNUZmMXTEaGzdm
#   CBwehqmk+iC+c8hA3Bbg6a2nAQnzb5DZi/CQKp5o5rK2Vh0zqeaDswqJbOCOONy4
#   4lbWgg9laT29yfkTsaflTZjB5XeHp76mrb+LgNZMMGwA8XgsUaFVe5haaP7UV3sO
#   yCB6G5tLCRLTOQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBSvEwk2lbtaf13OBwJ
#   eE2ykephudWtwCEvs4cml+WGDjtCeg9GN+SwSmqMvsyktPIhwjY0OZfJ9Vv1t5EM
#   UbcTq0Hw5Pc2SVNwjZGwPDczg2gHyVcdl1Hitz6VN8Zkp7K0p1Z2VP44OHpp3i0B
#   Q9RnXaImUg4Pq4KRcXrI6OHYEKIza/8B8hwboDpE+Vp9QSKHbAzPGe/QjuzQM8f4
#   J1+P3rh9MhdserEi1lG2oT5gW6Q+4jznwJx+aNJGqhqP2vo4OO2NECDq79Oqfm2O
#   0+QQND6YHhkQo8pQgdroXSVsNHgq9kNx5QKx+I8s5R2zdZbbHRNlcOg0BmP0f6OT
#   hpWu
#   -----END CERTIFICATE-----

# vault_ca_key: |
#   -----BEGIN PRIVATE KEY-----
#   MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCOGL1db6Ct5Frc
#   XeVN4ZvLciIP9cRtZ97USdyZ1H0Q8k19AUnbzoHpG6Jjjbrsa0ZvL3k8YOYIRKkM
#   MdyHhLRa/XRVWs3RPLq93fOSLiYBIVfaJnbVvAM4sHBfghtTrHZpoF6VWJw5kygR
#   DZUn+mMQ+274VN8WQJ8Jlt0YWXxxSX5vbbXS6qgXcarQJz9i+dWtuTvtGjoR6u3K
#   MOZcAnye6Mx+kyDTe9pC0yLTFXzHwKou3Du15qpwkXq1qlZagsw5jJosfFvpcDT9
#   Cr8CeY6xUJccLVi8UBu5fJATRhicaK1+815GTxBK247TDaCWSvLDi6Ok3xr7UiMz
#   /fSCJ8YrAgMBAAECggEAE+mjn9Rkz/mQQhFmcOOM0ZXM8C+gtzQ3Jci0AVqlrBpI
#   gZwMnaDy05fryceyyi6+UBZ3Bt8NXVtB1VOnc9ZE7/tUsiFndkrsYG8aEwIkkUP6
#   67c4L/uI+AjBtqCk87TXYzX2Cze/rNHSa5FbtZ6BA4A4rNQ37wZfQxjBIwhnR/iv
#   HU4nAbZZ6bYElRL6Ol/XphlKwyMH4Tl5l31+vFf3tct0+zSERwd/Smz6jbykB7Tw
#   0qjvSRiOHFe/gL0wQabYOGcUOUE9PPaPZY29ldJ3KZc0Gcxhp7uc2xdt0j53J3ml
#   zF4eG7d7T9L9pnhhT9FKcL2dAfZZwgtSQTbZOx2/AQKBgQDHTC81HA3jfOA5/7uN
#   rBP2BpOdwB4H0ZK7AAXCRSEUWmV7k2iJmOnvK4VpDXV9tcdr+PEovwtUENzQwHbM
#   kKMXNuBqheIFKS7V/9IExqMngx35dWu4Ru9DIdtMKYpI4NMGAHXMh3/QGPkQxpDg
#   MsYkl2en4hlRzdYn5Xe0DdJ4FwKBgQC2hlSup8WywyfJtBzF26J46K6DhAPqxhrL
#   vQmEmHpFGLeklGEELNyrQqs+00APATjIQbAmFduVH1HE7UQDIYla8No3q1tF2naL
#   sl/jKnE/JqlQd3e3+0CbTevxlKcIp34Xt3fs5ljd32xf501CY+RobexMDSjqZKVW
#   1PXnpaTbDQKBgQCs9zOpVjW/j2tTKt1tsUCJr1+B83CcvIgp/3UAC9sPvPyCaYa6
#   lJnC1vSsHeAwQAlZbe5uvI9qYFAkZEU2ePjydtAB4zwr2ngphiKRvotvCV6EWCIr
#   BnU0wDeBPDQl1+mNNe0GmzqUMnhG1O57hdVtgHGXxKTQ2GHask5XV/+n9QKBgETp
#   LHmQYASgx5nQhXhx9sJdXt3KbswppR48raZBBxClR1g8qPAxm9KQ5iRfD3VaybxZ
#   iI6oe/GuFGocBiyEcd5CxrBz4o7Z7x3I54jVklH8X7pAkJOGqZq47ZaUwAd1bRa5
#   Lu7i/LQv0TPYGQQywJ5ouejwovzzqLTCzGB72mTVAoGAEGkFHBa2CkvcIhFtiwuW
#   FwtrIBPo7mg/5lg95HqqEnbAckHxAytdlR0n3oRaVLPk5Fm6VHhfxtdZ7akajzby
#   lBNGeA2zOkTO9fpBoJfqS8VJUJXQnrh6OJdFjIELaa8s00zw/UMiPqDAvmiRXEQZ
#   wp51emFK4heEInuOFQwE4xQ=
#   -----END PRIVATE KEY-----

# vault_ca_crt: |
#   -----BEGIN CERTIFICATE-----
#   MIIDLTCCAhUCFHx+cHGEYcIxkejddtZNq4zR5X09MA0GCSqGSIb3DQEBCwUAMFMx
#   CzAJBgNVBAYTAkdCMR0wGwYDVQQKDBRkaWdpdGFsaXMuaW8gTGltaXRlZDEUMBIG
#   A1UECwwLVGVzdENsdXN0ZXIxDzANBgNVBAMMBnJvb3RDYTAeFw0yNTA2MTMxNTA1
#   MzJaFw0zNTA2MTExNTA1MzJaMFMxCzAJBgNVBAYTAkdCMR0wGwYDVQQKDBRkaWdp
#   dGFsaXMuaW8gTGltaXRlZDEUMBIGA1UECwwLVGVzdENsdXN0ZXIxDzANBgNVBAMM
#   BnJvb3RDYTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAI4YvV1voK3k
#   Wtxd5U3hm8tyIg/1xG1n3tRJ3JnUfRDyTX0BSdvOgekbomONuuxrRm8veTxg5ghE
#   qQwx3IeEtFr9dFVazdE8ur3d85IuJgEhV9omdtW8AziwcF+CG1OsdmmgXpVYnDmT
#   KBENlSf6YxD7bvhU3xZAnwmW3RhZfHFJfm9ttdLqqBdxqtAnP2L51a25O+0aOhHq
#   7cow5lwCfJ7ozH6TINN72kLTItMVfMfAqi7cO7XmqnCRerWqVlqCzDmMmix8W+lw
#   NP0KvwJ5jrFQlxwtWLxQG7l8kBNGGJxorX7zXkZPEErbjtMNoJZK8sOLo6TfGvtS
#   IzP99IInxisCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEABrGtEgNmFkJjEsnHcCg5
#   WcH0KV7EHaTamiji54qXUcBYEJmFry05vfo7tofM53ahV0pjQptS95d3svlqXacv
#   FiooX5sfjlTagUBDaNBeS0l6gZ20AOrjxGnELAmKCltEtLmAVXv+agxwb602gMIf
#   XB1lpjJXkguz1F9arkzvFPc07zdZME3NtGEKFNiVZmCmPXb5vaDdPALEhgSu38r3
#   l8fc5fngb4Gai8QYIXVvzDFDWDHAuALEZqRZfmtY33PYiikBA/noSSvORHRY0wBN
#   zvET1HUng/kJcsj8ddSGiCukARt3TPUPMampZGd+7G4pLvguWG97cqlt+7LWhnXa
#   vQ==
#   -----END CERTIFICATE-----
