---
- name: Apply Human ReadableID on {{ human_readableid.key }}
  axonops.axonops.human_readableid:
    org: "{{ org }}"
    cluster: "{{ human_readableid.key }}"
    present: "{{ human_readableid.present | default(true) }}"
    id: "{{ human_readableid.id | default('axon_agent_hostname') }}"
    auth_token: "{{ human_readableid.auth_token | default(omit) }}"
    username: "{{ human_readableid.username | default(omit) }}"
    password: "{{ human_readableid.password | default(omit) }}"
  with_items:
    "{{ human_readableid.value }}"
  tags:
  - axonops_human_readableid
  - human_readableid
  - readableid

# code: language=ansible
