---
- name: "Install logcollector on {{ logcollector.key }}"
  axonops.axonops.logcollector:
    org: "{{ org }}"
    cluster: "{{ logcollector.key }}"
    name: "{{ logcollector.name }}"
    interval: "{{ logcollector.interval | default('5s') }}"
    timeout: "{{ logcollector.timeout | default('1m') }}"
    filename: "{{ logcollector.filename }}"
    dateFormat: "{{ logcollector.dateFormat }}"
    readonly: "{{ logcollector.readonly | default(false) }}"
    present: "{{ logcollector.present | default(true) }}"
    auth_token: "{{ logcollector.auth_token | default(omit) }}"
    username: "{{ logcollector.username | default(omit) }}"
    password: "{{ logcollector.password | default(omit) }}"
  with_items:
    "{{ logcollector.value }}"
  tags:
  - axonops_logcollector
  - logcollectors
  - logcollector
  - logs
  - log

# code: language=ansible
