---
- name: Apply Slack Integration on  {{ slack_integration.key }}
  axonops.axonops.slack_integration:
    org: "{{ org }}"
    cluster: "{{ slack_integration.key }}"
    present: "{{ slack_integration.present | default(true) }}"
    name: "{{ slack_integration.name }}"
    webhook_url: "{{ slack_integration.webhook_url }}"
    auth_token: "{{ slack_integration.auth_token | default(omit) }}"
    username: "{{ slack_integration.username | default(omit) }}"
    password: "{{ slack_integration.password | default(omit) }}"
  with_items:
    "{{ slack_integration.value }}"
  tags:
  - axonops_slack_integration
  - slack_integration
  - integration
  - slack

# code: language=ansible
