- name: Installs and configures the Search backend for AxonOps Server
  hosts: axonops-searchdb
  become: true

  pre_tasks:
    # This is only for this example to work, please review your firewall settings and requirements
    - name: "Stop firewalld"
      ansible.builtin.systemd:
        name: firewalld
        enabled: false
        state: stopped
      when: ansible_os_family == 'RedHat'
      failed_when: false

  roles:
    - name: java
      role: axonops.axonops.java
      tags: java
    - role: axonops.axonops.elastic
      tags: elastic

# code: language=ansible
