- name: Deploy AxonOps Server
  hosts: axonops-server
  become: true

  pre_tasks:
    # This is only for this example to work, please review your firewall settings and requirements
    - name: "Stop firewalld"
      ansible.builtin.systemd:
        name: firewalld
        enabled: false
        state: stopped
      when: ansible_os_family == 'RedHat'
      failed_when: false

  roles:
    - role: axonops.axonops.server
      tags: server, axonops-server
    - role: axonops.axonops.dash
      tags: dash, axonops-dashboard

# code: language=ansible
