- name: Deploy AxonOps Server
  hosts: axon-server
  become: true
  vars:
    install_cassandra: true
    install_elastic: true
    axon_server_cql_hosts:
      - localhost:9042
    axon_dash_listen_address: 0.0.0.0
    cassandra_cluster_name: axonops
    cassandra_dc: default
    cassandra_rack: rack1
    axon_java_agent: "axon-cassandra5.0-agent-jdk17"
    axon_agent_server_host: localhost
    axon_agent_tls_mode: "disabled"
    axon_agent_customer_name: "mycompany"
    cassandra_start_on_boot: true
    cassandra_listen_address: "localhost"
    cassandra_rpc_address: "localhost"

    # For AxonOps server version >= 2.0.4, set this variable to use the new Elasticsearch syntax
    # axon_server_version: "2.0.4"

    # Legacy Elasticsearch configuration (used for server versions < 2.0.4)
    axon_server_elastic_host: "http://127.0.0.1"
    axon_server_elastic_port: "9200"


  pre_tasks:
    # This is only for this example to work, please review your firewall settings and requirements
    - name: "Stop firewalld"
      ansible.builtin.systemd:
        name: firewalld
        enabled: false
        state: stopped
      when: ansible_os_family == 'RedHat'
      failed_when: false

  roles:
    - name: java
      role: axonops.axonops.java
      tags: java
    - role: axonops.axonops.agent
      tags: agent, axonops-agent
    - role: axonops.axonops.cassandra
      tags: cassandra
      when: install_cassandra is defined and install_cassandra
    - role: axonops.axonops.elastic
      tags: elastic
      when: install_elastic is defined and install_elastic
    - role: axonops.axonops.server
      tags: server, axonops-server
    - role: axonops.axonops.dash
      tags: dash, axonops-dashboard

# code: language=ansible
