- name: Deploy AxonOps Agent
  hosts: cassandra
  become: true
  vars:
    install_cassandra: true
    axon_java_agent: "axon-cassandra4.1-agent"
    axon_agent_version: "2.0.2"
    axon_java_agent_version: "1.0.14"
    axon_agent_customer_name: "mycompany"
    # This is the AxonOps Server host, it can be localhost or the IP of the AxonOps Server
    # Leave empty if you want to use the SaaS environment
    axon_agent_server_host: "{{ groups['axon-server'] | first }}"
    axon_agent_tls_mode: "disabled"
    java_pkg: java-11-openjdk-headless
    cassandra_cluster_name: axonops
    cassandra_dc: "default"
    cassandra_rack: rack1
    # Set to false if you already have Apache Cassandra running

  pre_tasks:
    # This is only for this example to work, please review your firewall settings and requirements
    - name: "Stop firewalld"
      ansible.builtin.systemd:
        name: firewalld
        enabled: false
        state: stopped
      when: ansible_os_family == 'RedHat'
      failed_when: false

  roles:
    - name: preflight
      tags: preflight
      role: axonops.axonops.preflight
    - name: java
      role: axonops.axonops.java
      tags: java
    - role: axonops.axonops.agent
      tags: agent, axonops-agent
    - role: axonops.axonops.cassandra
      tags: cassandra
      when: install_cassandra
      vars:
        cassandra_seeds: "{{ groups['cassandra'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list | first }}"
        cassandra_listen_address: "{{ ansible_default_ipv4.address }}"
        cassandra_listen_interface: "{{ ansible_default_ipv4.interface }}"
        cassandra_rpc_address: "{{ ansible_default_ipv4.address }}"

  post_tasks:
    - name: Add axonops to the cassandra group
      tags: user
      ansible.builtin.user:
        name: cassandra
        groups: cassandra,axonops
        append: true
      notify:
        - Restart axon-agent
        - Restart Cassandra

# code: language=ansible
