---
- name: Set package name with version for Debian
  ansible.builtin.set_fact:
    axon_server_versioned_package: "axon-server={{ axon_server_version }}"
  when:
    - ansible_os_family == 'Debian'
    - axon_server_version is defined
    - axon_server_version != 'latest'

- name: Set package name with version for RedHat
  ansible.builtin.set_fact:
    axon_server_versioned_package: "axon-server-{{ axon_server_version }}"
  when:
    - ansible_os_family == 'RedHat'
    - axon_server_version is defined
    - axon_server_version != 'latest'

- name: Set package name without version (for latest)
  ansible.builtin.set_fact:
    axon_server_versioned_package: "axon-server"
  when:
    - axon_server_version is not defined or axon_server_version == 'latest'

- name: Ensure Axon server is installed.
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name: "{{ axon_server_versioned_package }}"
    state: "{{ axon_server_state }}"
  notify:
    - restart axon-server

- name: Ensure Axon server is installed.
  when: ansible_os_family == "RedHat"
  ansible.builtin.package:
    name: "{{ axon_server_versioned_package }}"
    state: "{{ axon_server_state }}"
    enablerepo: "axonops*"
    disablerepo: "*"
  notify:
    - restart axon-server

- name: Add systemd service override for axon-server when opensearch and cassandra are running on localhost
  when:
    - opensearch_network_host is defined and opensearch_network_host in ['localhost', '127.0.0.1']
    - cassandra_rpc_address is defined and cassandra_rpc_address in ['localhost', '127.0.0.1']
  block:
    - name: Create systemd override directory for axon-server
      ansible.builtin.file:
        path: /etc/systemd/system/axon-server.service.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Add systemd service override for axon-server
      ansible.builtin.copy:
        dest: /etc/systemd/system/axon-server.service.d/override.conf
        owner: root
        group: root
        mode: "0644"
        content: |
          [Service]
          After=network-online.target cassandra.service opensearch.service
      notify:
        - Reload systemd

- name: Gather installed package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Set installed axon-server version
  ansible.builtin.set_fact:
    installed_server_version: >-
      {{ (
        ansible_facts.packages['axon-server'][0].version
        if ansible_os_family == 'RedHat'
        else
        (ansible_facts.packages['axon-server'][0].version | split('-') | first)
      ) | default(omit) }}
  when:
    - axon_server_version == 'latest'
    - "'axon-server' in ansible_facts.packages"

- name: Set axon_server_version fact from installed version
  ansible.builtin.set_fact:
    axon_server_version: "{{ installed_server_version }}"
  when:
    - axon_server_version == 'latest'

# code: language=ansible
