---
galaxy_info:
  author: Digitalis.IO DevOps
  description: Digitalis Role for axon-server
  company: Digitalis.IO
  license: Apache License 2.0

  min_ansible_version: 2.9

  platforms:
    - name: RedHat
      versions:
        - 7
    - name: Debian
      versions:
        - 8
        - 9
    - name: Ubuntu
      versions:
        - 16.04
        - 18.04

  galaxy_tags:
    - axon-server

dependencies: []
