---
- name: Log in to container registry
  community.docker.docker_login:
    registry_url: "{{ devcluster_registry_auth.registry }}"
    username: "{{ devcluster_registry_auth.username }}"
    password: "{{ devcluster_registry_auth.password }}"
  no_log: true
