---
- name: Validate inputs
  ansible.builtin.import_tasks: validate.yml
  tags: [always]

- name: Install Docker (optional)
  ansible.builtin.include_role:
    name: axonops.axonops.docker
  when: devcluster_install_docker | bool
  tags: [docker]

- name: Authenticate to container registry
  ansible.builtin.include_tasks: auth.yml
  when: devcluster_registry_auth | length > 0
  tags: [auth]

- name: Render docker-compose file
  ansible.builtin.import_tasks: render.yml
  when: devcluster_state == 'present'
  tags: [render]

- name: Manage devcluster lifecycle
  ansible.builtin.import_tasks: manage.yml
  tags: [manage]
