---
- name: Converge
  hosts: all
  pre_tasks:
    # bug in the container we use for testing
    - name: "Create /usr/share/man/man1/"
      ansible.builtin.file:
        path: /usr/share/man/man1/
        state: directory
        recurse: true
        mode: "0755"
  roles:
    - role: java
      vars:
        java_use_zulu: true
