_cassandra_cqlai_binary: |-
  {% if ansible_architecture == 'x86_64' %}
  https://github.com/axonops/cqlai/releases/download/v{{ cassandra_cqlai_version }}/cqlai_{{ cassandra_cqlai_version }}_amd64.deb
  {% elif ansible_architecture == 'aarch64' %}
  https://github.com/axonops/cqlai/releases/download/v{{ cassandra_cqlai_version }}/cqlai_{{ cassandra_cqlai_version }}_arm64.deb
  {% else %}
  https://github.com/axonops/cqlai/releases/download/v{{ cassandra_cqlai_version }}/cqlai_{{ cassandra_cqlai_version }}_{{ ansible_architecture }}.deb
  {% endif %}
