---
- name: Converge
  hosts: all
  vars:
    ntp_prefered_server: time.cloudflare.com
    ntp_servers:
      - time.google.com
    ntp_pool_hosts:
      - 2.molecule.pool.ntp.org
    ntp_allowed_clients:
      - 10.0.0.0/8
    chrony_extra_options: "minpoll 4 maxpoll 6"
    chrony_extra_directives:
      - "leapsectz right/UTC"
  roles:
    - role: chrony

# code: language=ansible
