---
- name: Add OpenBao yum repository
  ansible.builtin.yum_repository:
    name: openbao
    description: OpenBao Stable - $basearch
    baseurl: https://packages.openbao.io/openbao/stable/centos/$releasever/$basearch
    gpgkey: https://packages.openbao.io/openbao-archive-keyring.gpg
    gpgcheck: true
    repo_gpgcheck: false
    enabled: true

# code: language=ansible
