name: Release collection

on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fail if tag is not prefixed by v
        run: |
          if [[ $GITHUB_REF_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9].* ]]; then
              echo "Valid version format"
          else
              echo "Invalid version format"
              exit 1
          fi

      - name: Check the galaxy.yml version has been updated
        run: |
          VERSION=$(echo $GITHUB_REF_NAME | sed 's/^v//g')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

          if ! grep -q "version: $VERSION" galaxy.yml; then
            echo "Please update galaxy.yml with the version $VERSION"
            exit 1
          fi

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          OPTIONS=""
          if [[ $GITHUB_REF_NAME == *"internal"* ]]; then
            OPTIONS="--prerelease"
          fi
          gh release create "$GITHUB_REF_NAME" \
              --repo="$GITHUB_REPOSITORY" \
              --title="Release for ${GITHUB_REF_NAME}" \
              --generate-notes $OPTIONS

  build:
    name: Package Ansible Galaxy collection
    runs-on: ubuntu-latest
    needs: [release]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install ansible
        run: sudo apt update && sudo apt-get -y install ansible
      - name: Package
        run: ansible-galaxy collection build
      - name: Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
