---
# Online installation
- name: Import OS specific variables
  ansible.builtin.include_tasks: "repo/{{ ansible_os_family }}.yml"
  tags:
    - axon_dash_repo

- name: Fuse is required for the dashboard in Redhat
  ansible.builtin.package:
    name: fuse
    state: present
  when: ansible_os_family == 'RedHat'

- name: Create service override path
  ansible.builtin.file:
    path: /etc/systemd/system/axon-dash.service.d
    state: directory
    mode: '0644'

- name: Create service override file
  ansible.builtin.template:
    src: axon-dash-service.j2
    dest: /etc/systemd/system/axon-dash.service.d/override.conf
    mode: '0644'
  notify: reload systemd

- name: Add version to the package name
  ansible.builtin.set_fact:
    axon_dash_versioned_package: "axon-dash-{{ axon_dash_version }}"
  when: axon_dash_version is defined and axon_dash_version != ''

- name: Ensure Axon Dashboard is installed.
  ansible.builtin.package:
    name: "{{ axon_dash_versioned_package | default('axon-dash') }}"
    state: "{{ axon_dash_state }}"
  notify:
    - restart axon-dash
  when: has_internet_access

# Offline installation
- name: Offline installation
  when: not has_internet_access and axon_dash_download_path is defined
  block:
    - name: Set RPM architecture variable
      ansible.builtin.set_fact:
        pkg_arch: >-
          {% if ansible_architecture == 'aarch64' %}aarch64{% else %}x86_64{% endif %}

    - name: Copy AxonOps Dashboard package to target
      ansible.builtin.copy:
        src: "{{ axon_dash_download_path }}"
        dest: "/tmp/axon-dash-{{ axon_dash_version }}.{{ pkg_arch }}.rpm"
        mode: "0644"
        owner: "{{ ansible_user | default('root') }}"
        group: "{{ ansible_user | default('root') }}"

    - name: Install AxonOps Dashboard offline
      ansible.builtin.package:
        name: "/tmp/axon-dash-{{ axon_dash_version }}.{{ pkg_arch }}.rpm"
        state: present
      notify:
        - restart axon-dash

- name: "Configure dashboard"
  ansible.builtin.template:
    src: axon-dash.yml.j2
    dest: /etc/axonops/axon-dash.yml
    mode: "0644"
  notify:
    - restart axon-dash

- name: Make sure the dashboard is started on boot
  when: axon_dash_start_at_boot
  ansible.builtin.service:
    name: axon-dash
    state: started
    enabled: true

- name: Nginx tasks
  ansible.builtin.import_tasks: nginx.yml
  when: axon_dash_nginx is defined and axon_dash_nginx.enabled
